version: '3.8'

services:
  frontend:
    build:
      context: ./frontend2
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm start

  backend:
    build:
      context: ./backend
    ports:
      - '50000:50000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=Admin
      - DB_PASSWORD=123456
      - DB_NAME=full-stack
      - DB_CONNECTION_OPTIONS="?allowPublicKeyRetrieval=true" # Add options if backend supports it
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: full-stack
      MYSQL_USER: Admin
      MYSQL_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password # Set authentication plugin
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
